In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

Array generation Function


In [2]:
arr = np.arange(1,11,3)
arr

array([ 1,  4,  7, 10])

In [3]:
#prefill the matrix with zeroes
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
#Prefill the matrix with 1
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
# prefill with any value
arr = np.full((3,4),67)
arr

array([[67, 67, 67, 67],
       [67, 67, 67, 67],
       [67, 67, 67, 67]])

In [6]:
# Identity Matrix
arr = np.eye((4))
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
# create a one-dimensional array of evenly and linearly spaced values over a specified interval
arr = np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Random Array Generation :-

In [8]:
# It generates x random numbers between 0 & 1.
np.random.rand(5)

array([0.21298781, 0.63387262, 0.74486213, 0.92791696, 0.6904241 ])

In [9]:
# np.random.randn(5) generates 5 random numbers from a standard normal distribution (mean=0, std=1),
# unlike rand() which is uniform [0,1)
np.random.randn(5)

array([-0.31915936,  0.41819771,  0.35064068, -1.66611651, -1.31593808])

In [10]:
# np.random.randint(3) generates a single random integer from 0 to 2 (upper limit is exclusive)
np.random.randint(3)

0

In [11]:
# Generates 10 random integers between 0 (inclusive) and 10 (exclusive)
np.random.randint(0,10,10)

array([1, 8, 9, 2, 5, 5, 7, 8, 3, 1], dtype=int32)

Properties:-(Array Attributes)

In [12]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int64
2


Array Methods:-

In [13]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr.min())

1


In [14]:
print(arr.max())

9


In [15]:
print(arr.sum())

45


Array Type conversion from int to float

In [16]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


Reshaping Arrays

In [17]:
arr = np.full((6,6),67)
arr.reshape(9,4)

flattened_arr = arr.flatten()  #Used to convert 2D --> 1D
print(flattened_arr)
flattened_arr.shape

[67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67
 67 67 67 67 67 67 67 67 67 67 67 67]


(36,)

Indexing

In [18]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr[1][1])

5


Fancy Indexing -->
  Access particular set of indexes at the same time.

In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9])
idx = [0,2,4]
arr[idx]

array([1, 3, 5])

Boolean Indexing!!!

In [20]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr[arr>2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5 6 7 8 9]
[2 4 6 8]
[1 3 5 7 9]


SLICING --> [Start: Stop: Step]

In [21]:
arr = np.array([1,2,3,4,5])

print(arr[0:5])
print(arr[0:5:2])
print(arr[::-1])

[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]


In [22]:
# arr[row_start:row_end, col_start:col_end]
# 0:2 → select row 0 and row 1
# 1:2 → select column 1 only

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr[0:2, 1:2]

array([[2],
       [5]])

📘 NumPy Axes (Dimensions)

🔹1D Array --> Has 1 axis
Referred to as: axis = 0

🔹 2D Array --> Has 2 axes

axis = 0 → Rows (vertical movement ⬇️)

axis = 1 → Columns (horizontal movement ➡️)

🔹 3D Array --> Has 3 axes

axis = 0 → Depth / Layers

axis = 1 → Rows (within each layer)

axis = 2 → Columns

In [23]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
# sum of columns
np.sum(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [24]:
np.sum(arr, axis=1) #Sum of Rows

array([ 6, 15, 24])

📘 3D NumPy Arrays (Indexing & Slicing)

In [25]:
# 🔹 Creating a 3D Array
arr3D = np.array([
  [[1, 2], [3, 4], [5, 6]],
  [[7, 8], [9, 10], [11, 12]]
])
arr3D.shape # →(2, 3, 2)-->(No. of layers, No.of Rows per layer, No. of columns per row)


(2, 3, 2)

In [26]:
# 🔹 Indexing in 3D Array
arr3D[1,1,0] #(2nd layer, 2nd Row, 1st Column)

np.int64(9)

In [27]:
# 🔹 Slicing in 3D Array
print(arr3D[:, 0, :]) # : -> All layers, 0-> 1st Row, : -> All columns
print(arr3D[:, :, 0])

[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


***Normalize***





In [28]:
arr = np.array([[1,2,3], [4,5,6]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized = (arr-mean)/std_dev
print(normalized)

[[-1.46385011 -0.87831007 -0.29277002]
 [ 0.29277002  0.87831007  1.46385011]]


Mathematical Functions

In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9])

# AGGREGATION

print(np.sum(arr))      # Returns the sum of all elements in the array
print(np.prod(arr))     # Returns the product (multiplication) of all elements
print(np.min(arr))      # Returns the smallest value in the array
print(np.mean(arr))     # Returns the average (mean) of the array
print(np.std(arr))      # Returns the standard deviation (spread of data)
print(np.var(arr))      # Returns the variance (square of standard deviation)
print(np.median(arr))   # Returns the middle value after sorting the array
print(np.argmin(arr))   # Returns the index of the smallest element
print(np.argmax(arr))   # Returns the index of the largest element

45
362880
1
5.0
2.581988897471611
6.666666666666667
5.0
0
8


In [30]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# AXIS CONCEPT:
# axis=0 → operate column-wise (down the rows ⬇️)
# axis=1 → operate row-wise (across columns ➡️)

# AGGREGATION WITH AXIS
                                                  # OUTPUT
print(np.sum(arr, axis=0))   # Sum of each column → [12, 15, 18]
print(np.sum(arr, axis=1))   # Sum of each row → [6, 15, 24]

print(np.min(arr, axis=0))   # Minimum in each column → [1, 2, 3]
print(np.min(arr, axis=1))   # Minimum in each row → [1, 4, 7]

print(np.max(arr, axis=0))   # Maximum in each column → [7, 8, 9]
print(np.max(arr, axis=1))   # Maximum in each row → [3, 6, 9]

print(np.mean(arr, axis=0))  # Mean of each column → [4., 5., 6.]
print(np.mean(arr, axis=1))  # Mean of each row → [2., 5., 8.]

print(np.std(arr, axis=0))   # Std deviation column-wise
print(np.std(arr, axis=1))   # Std deviation row-wise

print(np.var(arr, axis=0))   # Variance column-wise
print(np.var(arr, axis=1))   # Variance row-wise

print(np.argmin(arr, axis=0))  # Index of min in each column → [0, 0, 0]
print(np.argmin(arr, axis=1))  # Index of min in each row → [0, 0, 0]

print(np.argmax(arr, axis=0))  # Index of max in each column → [2, 2, 2]
print(np.argmax(arr, axis=1))  # Index of max in each row → [2, 2, 2]

[12 15 18]
[ 6 15 24]
[1 2 3]
[1 4 7]
[7 8 9]
[3 6 9]
[4. 5. 6.]
[2. 5. 8.]
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]
[6. 6. 6.]
[0.66666667 0.66666667 0.66666667]
[0 0 0]
[0 0 0]
[2 2 2]
[2 2 2]


***Power Functions***

In [31]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]


***Log and exponential***

In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [33]:
arr = np.array([1.2, 2.5, 3.7, 4.3, 5.8])

# ROUNDING FUNCTIONS

print(np.round(arr))     # Rounds to nearest integer (banker's rounding: .5 → nearest even)
print(np.floor(arr))     # Rounds DOWN to nearest integer
print(np.ceil(arr))      # Rounds UP to nearest integer
print(np.trunc(arr))     # Removes decimal part (towards zero)

[1. 2. 4. 4. 6.]
[1. 2. 3. 4. 5.]
[2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5.]


In [37]:
mohit = np.arange(1,31)
rai = mohit.reshape(5,6)

In [38]:
rai

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])